export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';
export const GET_SEARCH_PRODUTS = 'GET_SEARCH_PRODUTS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const CONTROLLER_CART_ITEM_COUNT = 'CONTROLLER_CART_ITEM_COUNT';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const DELETE_CART_ALL = 'DELETE_CART_ALL';
